### ISSUE TITLE
Remove package-lock.json from .gitignore

### ISSUE THREAD

**Issue by alex-page** [govau/service-manual#180]
We initially put the `package-lock.json` file into the `.gitignore` so that users of the service manual didn't accidentally commit it with their content changes.

This needs to be removed as we will one day want to lock versions so we have exact dependencies across all users of the service manual.

https://docs.npmjs.com/files/package-lock.json
> It describes the exact tree that was generated, such that subsequent installs are able to generate identical trees, regardless of intermediate dependency updates.

**Comment by dominikwilkowski** [comment]
hey @marksantoso ... Can you please remove the package-lock.json from the ignore? It is a secops requirement.

**Comment by marksantoso** [comment]
returned package
