### ISSUE TITLE
Breadcrumbs arrow showing repeat

### ISSUE THREAD

**Issue by dominikwilkowski** [govau/service-manual#60]
Breadcrumbs need:

```css
background-repeat: no-repeat;
```

<img width="163" alt="screen shot 2017-07-16 at 8 44 14 pm" src="https://user-images.githubusercontent.com/1266923/28246864-95003c64-6a67-11e7-8d6e-fb0c96afafe8.png">

**Comment by marksantoso** [comment]
This one is a ui-kit style fix

**Comment by dominikwilkowski** [comment]
Indeed... Just add an overwrite to our own styles and we fix it upstream soon
