### ISSUE TITLE
Request to remove focus state style for anchors

### ISSUE THREAD

**Issue by shad0wMe0w** [govau/service-manual#97]
@marksantoso @dominikwilkowski can we remove the black border style applied to the **focus** state of anchors? Several types of partials can get focus, and this makes the style stick out (in a bad way). If we need a focus state styled, let's revisit how it might look next sprint.

Some examples:
![screen shot 2017-07-18 at 2 10 17 pm](https://user-images.githubusercontent.com/8086823/28300461-e7b5a514-6bc2-11e7-81f5-f80a9a544fed.png)
![screen shot 2017-07-18 at 2 10 11 pm](https://user-images.githubusercontent.com/8086823/28300466-f0bcc0c0-6bc2-11e7-8b77-f82bbb60e412.png)
![screen shot 2017-07-18 at 2 10 00 pm](https://user-images.githubusercontent.com/8086823/28300473-f793ddb6-6bc2-11e7-8f97-8390e45ab8b9.png)

In action: https://service-manual.apps.staging.digital.gov.au/user-research/

**Comment by dominikwilkowski** [comment]
As a11y goes it is

A11Y > DESIGN

:)
